import "./globals.css";
import { Cairo } from "next/font/google";
import type { Metadata } from "next";

const cairo = Cairo({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;   // 👈 هنا تعريف النوع
}) {
  return (
    <html lang="en">
      <body className={cairo.className}>{children}</body>
    </html>
  );
}
